### PR TITLE
Add option to font organizer to find files recursively.

### PR DESCRIPTION
**Pull request by SolidTux**
This adds both an option to recursive find fonts for reorganization and also one to optionally delete empty folder that would be left behind.

### CODE REVIEW

**Comment by ftCLI** [comment]
Thanks again!

**Comment by SolidTux** [comment]
You mention the PRs in the release notes to 1.1.14, but they don't seem to be included.

**Comment by ftCLI** [comment]
Sorry, don't know what happened. I will merge the changes again and release a new version

**Comment by SolidTux** [comment]
No worries, that's not urgent! The commits are on the main branch, Im pretty sure it's just the release tag that points to a commit before the merge.

**Comment by ftCLI** [comment]
If it's ok, I'm removing the `--strip-foundry-option`. The soundry name should be always stripped, so I've implemented directly in the code

**Comment by ftCLI** [comment]
Done and released v1.1.15. Also added a check to skip renaming if `output_file == file`

**Comment by SolidTux** [comment]
> If it's ok, I'm removing the `--strip-foundry` option. The soundry name should be always stripped, so I've implemented directly in the code

Of course it's ok, it's your software, you can do whatever you want!

**Pull request merged**
